# Generated by Django 4.2.6 on 2023-10-18 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='room',
        ),
        migrations.AlterField(
            model_name='registers',
            name='room',
            field=models.CharField(max_length=120),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
