# Generated by Django 4.2.6 on 2024-11-20 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_inventory_room_registers_author_alter_item_barcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='room',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='registers',
            name='room',
            field=models.CharField(max_length=120),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
